# Generated by Django 4.2.2 on 2023-06-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=200)),
                ('card_category', models.CharField(choices=[('dev', 'Development'), ('torrents', 'Torrents'), ('media', 'Media')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Watch_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=200)),
                ('show_aka_name', models.CharField(max_length=200)),
                ('show_quality', models.CharField(choices=[('1080', 'High'), ('720', 'Medium')], max_length=50)),
            ],
        ),
    ]
