# Generated by Django 4.2.2 on 2023-06-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_url',
            field=models.CharField(default='https::/', max_length=200),
            preserve_default=False,
        ),
    ]
