# Generated by Django 4.2.2 on 2023-06-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_homepage', '0002_card_card_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=200)),
                ('show_aka_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Watch_List',
        ),
    ]
