# Generated by Django 4.2.2 on 2023-06-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_homepage', '0003_watch_delete_watch_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_icon',
            field=models.CharField(choices=[('code', 'Development'), ('download', 'Torrents'), ('film', 'Media')], default='code', max_length=100),
            preserve_default=False,
        ),
    ]
