# Generated by Django 4.2.2 on 2023-06-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_alternative_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
