# Generated by Django 4.2.2 on 2023-06-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0003_remove_volume_volume_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='volume_number',
            field=models.IntegerField(default=1),
        ),
    ]
