# Generated by Django 4.2.2 on 2023-06-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0004_alter_volume_volume_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='manga_status',
            field=models.CharField(choices=[('[V]', 'Completed'), ('[O]', 'Ongoing'), ('[!]', 'Unknown')], default='Unknown', max_length=250),
        ),
    ]
