# Generated by Django 4.2.2 on 2023-06-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0005_manga_manga_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Unknown', 'Unknown')], default='Unknown', max_length=250),
        ),
    ]
