# Generated by Django 4.2.2 on 2023-06-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0007_manga_manga_author_manga_manga_read_volumes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_author',
            field=models.CharField(max_length=200),
        ),
    ]
