# Generated by Django 4.2.2 on 2023-06-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0008_alter_manga_manga_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='manga_cover_picture',
            field=models.URLField(default='https://dw9to29mmj727.cloudfront.net/products/1569319006.jpg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manga',
            name='manga_reading_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('reading', 'Reading'), ('dropped', 'Dropped')], default='reading', max_length=250),
        ),
    ]
