# Generated by Django 4.2.2 on 2023-06-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0009_manga_manga_cover_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_reading_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('reading', 'Reading'), ('dropped', 'Dropped'), ('on_hold', 'On Hold')], default='reading', max_length=250),
        ),
    ]
