# Generated by Django 4.2.2 on 2023-06-14 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0012_delete_chapter_delete_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='manga_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
