# Generated by Django 4.2.2 on 2023-06-14 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0014_alter_manga_manga_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
