# Generated by Django 4.2.2 on 2023-06-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0015_alter_manga_manga_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
