# Generated by Django 4.2.2 on 2023-06-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0016_alter_manga_manga_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_alternative_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
