# Generated by Django 4.2.2 on 2023-06-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0021_remove_manhwa_manhwa_alternative_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhwa',
            name='manhwa_read_chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='manhwa_title',
            field=models.CharField(max_length=250),
        ),
    ]
