# Generated by Django 4.2.2 on 2023-06-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0022_manhwa_manhwa_read_chapters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhwa',
            name='manhwa_reading_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('reading', 'Reading'), ('dropped', 'Dropped'), ('on_hold', 'On Hold'), ('x', 'x')], default='reading', max_length=250),
        ),
        migrations.AddField(
            model_name='manhwa',
            name='manhwa_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('unknown', 'Unknown')], default='unknown', max_length=250),
        ),
    ]
