# Generated by Django 4.2.2 on 2023-06-14 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0024_rename_manga_cover_picture_manga_manga_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhwa',
            name='manga_id',
            field=models.CharField(default='aaaaa', max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]*$', 'Only letter characters are allowed.')]),
            preserve_default=False,
        ),
    ]
