# Generated by Django 4.2.2 on 2023-06-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0025_manhwa_manga_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manhwa',
            old_name='manga_id',
            new_name='manhwa_id',
        ),
    ]
