# Generated by Django 4.2.2 on 2023-06-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0026_rename_manga_id_manhwa_manhwa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_reading_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('reading', 'Reading'), ('dropped', 'Dropped'), ('on_hold', 'On Hold'), ('ptr', 'Planning To Read')], default='reading', max_length=250),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='manhwa_reading_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('reading', 'Reading'), ('dropped', 'Dropped'), ('on_hold', 'On Hold'), ('ptr', 'Planning To Read')], default='reading', max_length=250),
        ),
    ]
