# Generated by Django 4.2.2 on 2023-06-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manga', '0027_alter_manga_manga_reading_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='manga_reading_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Reading', 'Reading'), ('Dropped', 'Dropped'), ('On_hold', 'On Hold'), ('Planning_To_Read', 'Planning To Read')], default='reading', max_length=250),
        ),
        migrations.AlterField(
            model_name='manga',
            name='manga_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Unknown', 'Unknown')], default='unknown', max_length=250),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='manhwa_reading_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Reading', 'Reading'), ('Dropped', 'Dropped'), ('On_hold', 'On Hold'), ('Planning_To_Read', 'Planning To Read')], default='reading', max_length=250),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='manhwa_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Unknown', 'Unknown')], default='unknown', max_length=250),
        ),
    ]
